name: file_preview
description: Generate a thumbnail for a file based on the file extension. Uses the native files previewer on iOS.
version: 0.0.1+1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  native_pdf_renderer: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.dcc.file_preview
    pluginClass: FilePreviewPlugin